// src/components/Shared/playersData.js

const TeamPlayerCardData = [
    {
        name: "John Deo",
        age: 36,
        nationality: "Argentina",
        position: "Forward",
        totalGoals: 10,
        assists: 5,
        points: 8,
        image: "/public/assets/accountsetting.jpg",
    },
    {
        name: "Leo Messi",
        age: 34,
        nationality: "Argentina",
        position: "Midfielder",
        totalGoals: 15,
        assists: 10,
        points: 20,
        image: "/public/assets/user-2.jpg",
    },
    {
        name: "Cristiano Ronaldo",
        age: 38,
        nationality: "Portugal",
        position: "Forward",
        totalGoals: 25,
        assists: 7,
        points: 30,
        image: "/public/assets/user-3.jpg",
    },
    {
        name: "Neymar Jr.",
        age: 31,
        nationality: "Brazil",
        position: "Winger",
        totalGoals: 12,
        assists: 8,
        points: 15,
        image: "/public/assets/user-4.jpg",
    },
    {
        name: "Neymar Jr.",
        age: 31,
        nationality: "Brazil",
        position: "Winger",
        totalGoals: 12,
        assists: 8,
        points: 15,
        image: "/public/assets/user-4.jpg",
    },
    {
        name: "Neymar Jr.",
        age: 31,
        nationality: "Brazil",
        position: "Winger",
        totalGoals: 12,
        assists: 8,
        points: 15,
        image: "/public/assets/user-4.jpg",
    },
    {
        name: "Neymar Jr.",
        age: 31,
        nationality: "Brazil",
        position: "Winger",
        totalGoals: 12,
        assists: 8,
        points: 15,
        image: "/public/assets/user-4.jpg",
    },
    {
        name: "Neymar Jr.",
        age: 31,
        nationality: "Brazil",
        position: "Winger",
        totalGoals: 12,
        assists: 8,
        points: 15,
        image: "/public/assets/user-4.jpg",
    },
];

export default TeamPlayerCardData;
